# Generated by Django 5.2.1 on 2025-06-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_api", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_profile_setup_completed",
            field=models.BooleanField(default=False),
        ),
    ]
